version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./music:/app/music
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python app.py